#' Plot a Plant-Centric Pollen Sharing Network
#'
#' This function visualizes the pollen co-deposition network among plant species
#' in a circular layout.
#'
#' @details
#' The function first creates a stigma-by-plant matrix from the pollen data.
#' It then projects this into a plant-by-plant network, where the edge weight
#' between two plants represents the number of stigmas on which their pollen
#' was found together.
#'
#' @param years A numeric vector of years to include in the plot.
#' @param focal_plant A character string specifying a plant code (e.g., "Suc_pra")
#'   to highlight in the network plot.
#' @param colors A named list of colors for the plot components.
#' @param vertex_size_transform A function that takes a vector of total pollen
#'   counts per plant and returns a vector of vertex sizes. This allows for custom
#'   scaling of nodes. Defaults to `function(pollen) 5 * sqrt(pollen)`.
#' @param edge_width_transform A function that takes a vector of edge weights
#'   (co-occurrences) and returns a vector of edge widths. This allows for custom
#'   scaling of edges. Defaults to `function(weight) 0.5 * weight`.
#'
#' @return A plot generated by `igraph`.
#' @export
#' @importFrom igraph graph_from_incidence_matrix bipartite_projection V "V<-" E "E<-" strength layout_in_circle plot.igraph .inc
#' @importFrom dplyr %>%
#'
plot_pollen_network <- function(years, focal_plant = NULL,
                                colors = list(
                                  plant = "lightseagreen",
                                  edge = rgb(104, 99, 219, max = 255, alpha = 80),
                                  focal_plant = "gold",
                                  focal_edge = "red"
                                ),
                                # --- ADDED ARGUMENTS ---
                                vertex_size_transform = function(pollen) 5 * sqrt(pollen),
                                edge_width_transform = function(weight) 0.5 * weight) {

  # --- 1. Prepare Data ---
  network_subset <- pollen_network_data %>%
    dplyr::filter(year %in% years)

  if (nrow(network_subset) == 0) {
    warning("No pollen data found for the specified years.")
    return(NULL)
  }

  # --- 2. Construct the Stigma x Plant Matrix ---
  incidence_matrix <- network_subset %>%
    dplyr::mutate(present = 1) %>%
    tidyr::pivot_wider(
      id_cols = stigma_id,
      names_from = plant_code,
      values_from = present,
      values_fill = 0
    ) %>%
    tibble::column_to_rownames(var = "stigma_id") %>%
    as.matrix()

  if (ncol(incidence_matrix) < 2) {
    warning("Network requires at least two plant species. Cannot plot.")
    return(NULL)
  }

  # --- 3. Create Graph and Project to Plant-Plant Network ---
  bipartite_graph <- igraph::graph_from_incidence_matrix(incidence_matrix)
  plant_network <- igraph::bipartite_projection(bipartite_graph, which = "true", multiplicity = TRUE)

  # --- 4. Set Node and Edge Attributes ---
  # Size nodes by total pollen count (degree)
  total_pollen <- colSums(incidence_matrix)

  # --- CHANGED: Apply the user-defined function for vertex size ---
  igraph::V(plant_network)$size <- vertex_size_transform(total_pollen[igraph::V(plant_network)$name])

  # Set colors
  igraph::V(plant_network)$color <- colors$plant
  igraph::E(plant_network)$color <- colors$edge

  if (!is.null(focal_plant) && focal_plant %in% igraph::V(plant_network)$name) {
    igraph::V(plant_network)$color <- ifelse(igraph::V(plant_network)$name == focal_plant, colors$focal_plant, colors$plant)
    focal_edges <- igraph::E(plant_network)[.inc(focal_plant)]
    igraph::E(plant_network)$color[focal_edges] <- colors$focal_edge
  }

  # --- 5. Plot the Network ---
  plot(
    plant_network,
    layout = igraph::layout_in_circle,
    vertex.label = igraph::V(plant_network)$name,
    vertex.label.cex = 0.9,
    vertex.label.color = "black",
    # --- CHANGED: Apply the user-defined function for edge width ---
    edge.width = edge_width_transform(igraph::E(plant_network)$weight)
  )
}
