#' Plot a Bipartite Plant-Pollinator Interaction Network
#'
#' This function takes interaction data, constructs a quantitative interaction matrix,
#' and uses the bipartite package to create a network visualization.
#'
#' @param focal_plant A character string specifying a plant code (e.g., "Suc_pra")
#'   to highlight in the network plot. If `NULL` (the default), all interactions
#'   are shown in the standard color.
#' @param ... Filtering arguments passed directly to `get_interaction_data()` to
#'   define the network to be plotted (e.g., `years = 22`, `is_pollinator = TRUE`).
#'
#' @return A plot generated by `bipartite::plotweb()`.
#' @export
#' @importFrom bipartite plotweb
#' @importFrom dplyr %>%
#'
plot_interaction_network <- function(focal_plant = NULL, ...) {

  # --- 1. Get and Prepare Data ---
  # Get standardized data based on user's filters (...)
  interaction_subset <- get_interaction_data(standardize = TRUE, ...)

  if (nrow(interaction_subset) == 0) {
    warning("No interaction data found for the specified filters. Cannot plot network.")
    return(NULL)
  }

  # --- 2. Construct the Interaction Matrix ---
  # We'll use the standardized 'rate' as the weight of the interaction
  network_matrix <- interaction_subset %>%
    # Group by plant and pollinator, summing rates across all other variables
    dplyr::group_by(.data$plant_code, .data$pollinator_id) %>%
    dplyr::summarise(total_rate = sum(.data$rate, na.rm = TRUE), .groups = 'drop') %>%
    # Create the wide matrix with plants as rows and pollinators as columns
    tidyr::pivot_wider(
      names_from = .data$pollinator_id,
      values_from = .data$total_rate,
      values_fill = 0
    ) %>%
    tibble::column_to_rownames(var = "plant_code")

  # --- 3. Set Colors for Focal Species Highlight ---
  # Default colors
  plant_color <- "lightseagreen"
  pollinator_color <- "lightcoral"
  interaction_color <- rgb(150, 150, 150, max = 255, alpha = 60) # Semi-transparent grey

  if (!is.null(focal_plant) && focal_plant %in% rownames(network_matrix)) {
    # If a focal plant is specified, create a color vector
    plant_color <- ifelse(rownames(network_matrix) == focal_plant, "gold", "lightseagreen")

    # Find pollinators that interact with the focal plant
    focal_pollinators <- colnames(network_matrix)[network_matrix[focal_plant, ] > 0]
    pollinator_color <- ifelse(colnames(network_matrix) %in% focal_pollinators, "gold", "lightcoral")
  }

  # --- 4. Plot the Network ---
  # Use try() to catch potential errors from plotweb if the matrix is too sparse
  try(
    bipartite::plotweb(
      network_matrix,
      method = "normal",
      text.rot = 90,
      labsize = 1.2,
      y.width.low = 0.05,
      y.width.high = 0.05,
      col.low = plant_color,
      col.high = pollinator_color,
      bor.col.interaction = interaction_color,
      col.interaction = interaction_color
    )
  )
}
