#' Plot a Plant-Centric Pollinator Sharing Network
#'
#' This function visualizes the pollinator sharing network between plant species
#' in a circular layout.
#'
#' @param size_by A character string: `"interactions"` (the default) or `"abundance"`.
#' @param focal_plant A character string specifying a plant code to highlight.
#' @param plant_abundance_data A data frame of standardized plant abundance.
#' @param colors A named list of colors for the plot components.
#' @param ... Filtering arguments passed directly to `get_interaction_data()`.
#'
#' @return A plot generated by `igraph`.
#' @export
#' @importFrom igraph graph_from_incidence_matrix bipartite_projection V "V<-" E "E<-" strength layout_in_circle plot.igraph
#' @importFrom dplyr %>%
#'
plot_plant_sharing_network <- function(size_by = "interactions",
                                       focal_plant = NULL,
                                       plant_abundance_data = NULL,
                                       colors = list(
                                         plant = "lightseagreen",
                                         edge = rgb(104, 99, 219, max = 255, alpha = 80),
                                         focal_plant = "gold",
                                         focal_edge = "red"
                                       ),
                                       ...) {

  # --- Input Validation and Data Prep ---
  # (This part is unchanged)
  if (size_by == "abundance" && is.null(plant_abundance_data)) {
    stop("`plant_abundance_data` must be provided when `size_by = 'abundance'`.")
  }
  interaction_subset <- get_interaction_data(remove_zeros = TRUE, ...)
  if (nrow(interaction_subset) == 0) {
    warning("No interaction data found for filters. Cannot plot network.")
    return(NULL)
  }

  # --- Construct the Bipartite Network Matrix ---
  # (This part is unchanged)
  network_matrix <- interaction_subset %>%
    dplyr::filter(!is.na(.data$plant_code)) %>%
    dplyr::group_by(.data$plant_code, .data$pollinator_id) %>%
    dplyr::summarise(n = sum(.data$interaction_count, na.rm = TRUE), .groups = 'drop') %>%
    tidyr::pivot_wider(
      names_from = .data$pollinator_id,
      values_from = .data$n,
      values_fill = 0
    ) %>%
    tibble::column_to_rownames(var = "plant_code")
  if (nrow(network_matrix) < 2) {
    warning("Network requires at least two plant species. Cannot plot.")
    return(NULL)
  }

  # --- Create Graph and Project to Plant Network ---
  # (This part is unchanged)
  bipartite_graph <- igraph::graph_from_incidence_matrix(network_matrix, weighted = TRUE)
  plant_network <- igraph::bipartite_projection(bipartite_graph, which = "false", multiplicity = TRUE)

  # --- Set Node Sizes ---
  # (This part is unchanged)
  if (size_by == "abundance") {
    filtered_years <- unique(interaction_subset$year)
    plant_sizes <- plant_abundance_data %>%
      dplyr::filter(year %in% filtered_years) %>%
      dplyr::select(-year, -plot_id) %>%
      colSums(na.rm = TRUE)

    igraph::V(plant_network)$size <- 5 * sqrt(plant_sizes[igraph::V(plant_network)$name])

  } else {
    igraph::V(plant_network)$size <- 5 * sqrt(igraph::strength(plant_network, weights = igraph::E(plant_network)$weight))
  }
  igraph::V(plant_network)$size[is.na(igraph::V(plant_network)$size)] <- 2

  # --- Set Colors for Focal Highlight ---
  igraph::V(plant_network)$color <- colors$plant
  igraph::E(plant_network)$color <- colors$edge

  if (!is.null(focal_plant) && focal_plant %in% igraph::V(plant_network)$name) {
    igraph::V(plant_network)$color <- ifelse(igraph::V(plant_network)$name == focal_plant, colors$focal_plant, colors$plant)

    # --- FIX: Use .inc() instead of the outdated inc() ---
    focal_edges <- igraph::E(plant_network)[.inc(focal_plant)]

    igraph::E(plant_network)$color[focal_edges] <- colors$focal_edge
  }

  # --- Plot the Network ---
  # (This part is unchanged)
  plot(
    plant_network,
    layout = igraph::layout_in_circle,
    vertex.label = igraph::V(plant_network)$name,
    vertex.label.cex = 0.8,
    vertex.label.color = "black",
    edge.width = igraph::E(plant_network)$weight * 0.4
  )
}
