#' Plot a Bipartite Plant-Pollinator Interaction Network
#'
#' This function takes interaction data, constructs a quantitative interaction matrix,
#' and uses the bipartite package to create a network visualization.
#'
#' @param focal_plant A character string specifying a plant code (e.g., "Suc_pra")
#'   to highlight in the network plot. If `NULL` (the default), all interactions
#'   are shown in the standard color.
#' @param ... Filtering arguments passed directly to `get_interaction_data()` to
#'   define the network to be plotted (e.g., `years = 22`, `is_pollinator = TRUE`).
#'
#' @return A plot generated by `bipartite::plotweb()`.
#' @export
#' @importFrom bipartite plotweb
#' @importFrom dplyr %>%
#'
plot_interaction_network <- function(focal_plant = NULL, ...) {

  # --- 1. Get and Prepare Data ---
  # Get standardized data based on user's filters (...)
  # The default `remove_zeros = TRUE` in get_interaction_data should handle this,
  # but we add an explicit filter below for maximum safety.
  interaction_subset <- get_interaction_data(standardize = TRUE, ...)

  if (nrow(interaction_subset) == 0) {
    warning("No interaction data found for the specified filters. Cannot plot network.")
    return(NULL)
  }

  # --- 2. Construct the Interaction Matrix ---
  network_matrix <- interaction_subset %>%
    # --- FIX: Explicitly remove rows with no plant code ---
    dplyr::filter(!is.na(.data$plant_code)) %>%
    dplyr::group_by(.data$plant_code, .data$pollinator_id) %>%
    dplyr::summarise(total_rate = sum(.data$rate, na.rm = TRUE), .groups = 'drop') %>%
    tidyr::pivot_wider(
      names_from = .data$pollinator_id,
      values_from = .data$total_rate,
      values_fill = 0
    ) %>%
    tibble::column_to_rownames(var = "plant_code")

  # --- 3. Set Colors for Focal Species Highlight ---
  # (This section is unchanged)
  plant_color <- "lightseagreen"
  pollinator_color <- "lightcoral"
  interaction_color <- rgb(150, 150, 150, max = 255, alpha = 60)

  if (!is.null(focal_plant) && focal_plant %in% rownames(network_matrix)) {
    plant_color <- ifelse(rownames(network_matrix) == focal_plant, "gold", "lightseagreen")
    focal_pollinators <- colnames(network_matrix)[network_matrix[focal_plant, ] > 0]
    pollinator_color <- ifelse(colnames(network_matrix) %in% focal_pollinators, "gold", "lightcoral")
  }

  # --- 4. Plot the Network ---
  # (This section is unchanged)
  try(
    bipartite::plotweb(
      network_matrix,
      method = "normal",
      text.rot = 90,
      labsize = 1.2,
      y.width.low = 0.05,
      y.width.high = 0.05,
      col.low = plant_color,
      col.high = pollinator_color,
      bor.col.interaction = interaction_color,
      col.interaction = interaction_color
    )
  )
}
